"""Initial migration

Revision ID: 86372709aa3f
Revises: 
Create Date: 2026-02-04 11:10:47.524263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86372709aa3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddIngredientsRecipes',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('IngredientID', sa.Integer(), nullable=True),
    sa.Column('RecipeID', sa.Integer(), nullable=True),
    sa.Column('Must', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Ingredients',
    sa.Column('IngredientID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('is_present', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('average_shelf_life', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('IngredientID')
    )
    op.create_table('IngredientsRecipes',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('IngredientID', sa.Integer(), nullable=True),
    sa.Column('RecipeID', sa.Integer(), nullable=True),
    sa.Column('Must', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('Recipes',
    sa.Column('RecipeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RecipeName', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('CookingTime', sa.Integer(), nullable=True),
    sa.Column('ImageURL', sa.String(length=255), nullable=True),
    sa.Column('Ingredients', sa.Text(), nullable=True),
    sa.Column('Instructions', sa.Text(), nullable=True),
    sa.Column('IngredientsAmount', sa.Text(), nullable=True),
    sa.Column('Calorie', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Salt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Protein', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('VegetableIntake', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ChangedUnit', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('RecipeID')
    )
    op.create_table('unit_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FoodName', sa.String(length=255), nullable=True),
    sa.Column('Unit', sa.String(length=50), nullable=True),
    sa.Column('Weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('IngredientSubstitutes',
    sa.Column('SubstituteID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RecipeID', sa.Integer(), nullable=True),
    sa.Column('PrimaryIngredientID', sa.Integer(), nullable=True),
    sa.Column('SubstituteIngredientID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['PrimaryIngredientID'], ['Ingredients.IngredientID'], ),
    sa.ForeignKeyConstraint(['RecipeID'], ['Recipes.RecipeID'], ),
    sa.ForeignKeyConstraint(['SubstituteIngredientID'], ['Ingredients.IngredientID'], ),
    sa.PrimaryKeyConstraint('SubstituteID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IngredientSubstitutes')
    op.drop_table('unit_conversion')
    op.drop_table('Recipes')
    op.drop_table('IngredientsRecipes')
    op.drop_table('Ingredients')
    op.drop_table('AddIngredientsRecipes')
    # ### end Alembic commands ###
